In [22]:
import pandas as pd

In [30]:
data = pd.read_csv("EPL_20_21.csv")

In [31]:
data

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0
1,Edouard Mendy,Chelsea,SEN,GK,28,31,31,2745,0,0,1007,84.6,0,0,0.00,0.00,2,0
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0
3,Ben Chilwell,Chelsea,ENG,DF,23,27,27,2286,3,5,1806,78.6,0,0,0.10,0.11,3,0
4,Reece James,Chelsea,ENG,DF,20,32,25,2373,1,2,1987,85.0,0,0,0.06,0.12,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,Lys Mousset,Sheffield United,FRA,"FW,MF",24,11,2,296,0,0,50,80.0,0,0,0.22,0.10,0,0
528,Jack O'Connell,Sheffield United,ENG,DF,26,2,2,180,0,0,77,77.9,0,0,0.00,0.00,0,0
529,Iliman Ndiaye,Sheffield United,FRA,MF,21,1,0,12,0,0,3,100.0,0,0,0.00,0.00,0,0
530,Antwoine Hackford,Sheffield United,ENG,"DF,FW",16,1,0,11,0,0,1,100.0,0,0,1.16,0.00,0,0
531,Femi Seriki,Sheffield United,ENG,DF,17,1,0,1,0,0,0,-1.0,0,0,0.00,0.00,0,0

In [85]:
data = pd.read_csv("EPL_20_21.csv")

In [106]:
data[(data['Age']>=30) & (data['Goals']>=10)]

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
63,Edinson Cavani,Manchester United,URU,FW,33,26,13,1375,10,3,343,78.7,0,0,0.48,0.17,4,0
110,Jamie Vardy,Leicester City,ENG,FW,33,34,31,2840,15,9,452,66.4,8,9,0.62,0.16,1,0
143,Michail Antonio,West Ham United,ENG,FW,30,26,24,1974,10,5,490,66.5,0,0,0.52,0.11,3,0
175,Gareth Bale,Tottenham Hotspur,WAL,FW,31,20,10,920,11,2,408,69.6,0,0,0.52,0.19,1,0
187,Pierre-Emerick Aubameyang,Arsenal,GAB,FW,31,29,26,2332,10,3,691,75.0,2,2,0.41,0.11,2,0