In [22]:
import pandas as pd

In [30]:
data = pd.read_csv("EPL_20_21.csv")

In [31]:
data

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0
1,Edouard Mendy,Chelsea,SEN,GK,28,31,31,2745,0,0,1007,84.6,0,0,0.00,0.00,2,0
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0
3,Ben Chilwell,Chelsea,ENG,DF,23,27,27,2286,3,5,1806,78.6,0,0,0.10,0.11,3,0
4,Reece James,Chelsea,ENG,DF,20,32,25,2373,1,2,1987,85.0,0,0,0.06,0.12,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,Lys Mousset,Sheffield United,FRA,"FW,MF",24,11,2,296,0,0,50,80.0,0,0,0.22,0.10,0,0
528,Jack O'Connell,Sheffield United,ENG,DF,26,2,2,180,0,0,77,77.9,0,0,0.00,0.00,0,0
529,Iliman Ndiaye,Sheffield United,FRA,MF,21,1,0,12,0,0,3,100.0,0,0,0.00,0.00,0,0
530,Antwoine Hackford,Sheffield United,ENG,"DF,FW",16,1,0,11,0,0,1,100.0,0,0,1.16,0.00,0,0
531,Femi Seriki,Sheffield United,ENG,DF,17,1,0,1,0,0,0,-1.0,0,0,0.00,0.00,0,0

In [48]:
data = pd.read_csv("EPL_20_21.csv")

In [60]:
data.groupby(by="Club").mean()

,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
Club,,,,,,,,,,,,,,
Arsenal,24.965517,18.344828,14.413793,1291.482759,1.827586,1.310345,734.172414,81.262069,0.206897,0.206897,0.126207,0.083448,1.689655,0.172414
Aston Villa,24.291667,21.208333,17.416667,1563.833333,2.166667,1.583333,689.833333,76.795833,0.208333,0.250000,0.136667,0.085000,2.958333,0.166667
Brighton,24.555556,19.481481,15.481481,1391.703704,1.444444,0.888889,720.592593,71.988889,0.222222,0.333333,0.125556,0.087407,1.814815,0.222222
Burnley,27.040000,19.960000,16.720000,1504.800000,1.280000,0.800000,601.720000,67.456000,0.120000,0.120000,0.086800,0.045200,1.920000,0.000000
Chelsea,25.592593,19.481481,15.481481,1389.259259,2.074074,1.407407,931.518519,84.033333,0.296296,0.370370,0.137037,0.085926,1.888889,0.111111
Crystal Palace,28.333333,21.375000,17.416667,1566.416667,1.625000,1.208333,628.833333,74.529167,0.125000,0.166667,0.067500,0.045417,2.333333,0.083333
Everton,25.413793,18.068966,14.413793,1296.551724,1.551724,1.103448,629.172414,79.520690,0.137931,0.172414,0.085172,0.061379,2.034483,0.068966
Fulham,25.035714,18.857143,14.928571,1340.750000,0.928571,0.642857,673.571429,81.710714,0.107143,0.214286,0.106786,0.059643,2.392857,0.107143
Leeds United,25.347826,22.826087,18.173913,1633.652174,2.608696,1.956522,871.434783,79.382609,0.173913,0.173913,0.116522,0.086957,2.652174,0.043478
Leicester City,25.592593,19.148148,15.481481,1393.333333,2.370370,1.666667,761.925926,79.240741,0.370370,0.444444,0.124074,0.080370,2.259259,0.000000
Liverpool FC,25.571429,18.642857,14.928571,1343.571429,2.321429,1.535714,911.642857,83.453571,0.214286,0.214286,0.138214,0.097143,1.428571,0.000000
Manchester City,25.708333,20.625000,17.416667,1562.166667,3.416667,2.291667,1112.000000,86.733333,0.208333,0.375000,0.161667,0.105000,1.916667,0.083333
Manchester United,23.862069,17.827586,14.413793,1295.068966,2.413793,1.758621,757.241379,81.662069,0.344828,0.379310,0.108966,0.087931,2.206897,0.034483
Newcastle United,26.074074,19.518519,15.481481,1389.629630,1.629630,0.962963,526.592593,75.085185,0.222222,0.259259,0.098148,0.057407,2.407407,0.111111
Sheffield United,24.814815,19.296296,15.481481,1387.259259,0.703704,0.481481,586.777778,74.037037,0.111111,0.148148,0.135926,0.049259,2.703704,0.111111
Southampton,24.137931,17.896552,14.413793,1291.206897,1.620690,1.137931,646.931034,72.955172,0.172414,0.206897,0.081724,0.054828,1.793103,0.103448
Tottenham Hotspur,25.625000,22.083333,17.416667,1566.833333,2.750000,2.083333,828.000000,76.004167,0.208333,0.208333,0.129167,0.075000,2.375000,0.083333
West Bromwich Albion,26.766667,17.400000,13.933333,1246.700000,1.100000,0.666667,454.866667,72.383333,0.133333,0.133333,0.080333,0.039667,1.700000,0.133333
West Ham United,27.500000,21.541667,17.416667,1564.750000,2.500000,1.916667,681.583333,76.495833,0.083333,0.166667,0.114583,0.087500,2.083333,0.125000
Wolverhampton Wanderers,24.444444,19.407407,15.481481,1393.296296,1.259259,0.777778,691.148148,81.318519,0.148148,0.148148,0.114815,0.085926,2.037037,0.037037